import { Activity, ArrowDownRight, ArrowUpRight, BrainCircuit } from "lucide-react";
import { ValueAuditSummary } from "@/components/ValueOpportunityTable";
import { getGreenAiReport } from "@/services/greenAiEngine";
import { buildValueReport } from "@/services/valueEngine";

export const dynamic = "force-dynamic";

export default async function GreenAiReportPage() {
  const [report, valueReport] = await Promise.all([getGreenAiReport(), buildValueReport()]);
  return <>
    <div className="mb-7"><p className="label mb-2 text-neon">Relatório executivo AI</p><h1 className="text-3xl font-black tracking-tight md:text-4xl">Evolução e performance histórica</h1><p className="mt-2 max-w-3xl text-sm text-zinc-500">Leitura probabilística do modelo, mercados e backtests baseada exclusivamente nos registros disponíveis.</p></div>
    <section className="mb-6"><ValueAuditSummary {...valueReport.audit}/></section>
    <div className="grid gap-4 md:grid-cols-3">{report.backtests.map((item) => <div className="card p-5" key={item.period}><Activity className="text-neon"/><p className="mt-4 text-xs font-black">{item.period}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><p className="label">ROI</p><strong className={item.roi >= 0 ? "text-neon" : "text-red-400"}>{item.roi.toFixed(2)}%</strong></div><div><p className="label">Yield</p><strong>{item.yield.toFixed(2)}%</strong></div><div><p className="label">Win Rate</p><strong>{item.winRate.toFixed(1)}%</strong></div><div><p className="label">Lucro</p><strong>{item.profit.toFixed(2)}u</strong></div><div><p className="label">Drawdown</p><strong className="text-red-400">{item.drawdown.toFixed(2)}u</strong></div><div><p className="label">Entradas</p><strong>{item.entries}</strong></div></div></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="card p-5"><div className="flex items-center gap-3"><ArrowUpRight className="text-neon"/><div><p className="label">Melhores mercados</p><h2 className="text-lg font-black">Ranking por ROI</h2></div></div><div className="mt-5 space-y-3">{report.bestMarkets.length ? report.bestMarkets.map((item,index) => <div key={item.period} className="grid grid-cols-[28px_1fr_auto] items-center rounded-xl border border-line p-3 text-xs"><span className="text-zinc-600">{index+1}</span><b>{item.period}</b><span className="text-neon">{item.roi.toFixed(2)}%</span></div>) : <p className="text-xs text-zinc-600">Dataset ainda sem mercados liquidados.</p>}</div></section><section className="card p-5"><div className="flex items-center gap-3"><ArrowDownRight className="text-red-400"/><div><p className="label">Piores mercados</p><h2 className="text-lg font-black">Pontos de atenção</h2></div></div><div className="mt-5 space-y-3">{report.worstMarkets.length ? report.worstMarkets.map((item,index) => <div key={item.period} className="grid grid-cols-[28px_1fr_auto] items-center rounded-xl border border-line p-3 text-xs"><span className="text-zinc-600">{index+1}</span><b>{item.period}</b><span className={item.roi >= 0 ? "text-neon" : "text-red-400"}>{item.roi.toFixed(2)}%</span></div>) : <p className="text-xs text-zinc-600">Dataset ainda sem mercados liquidados.</p>}</div></section></div>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-line p-5"><p className="text-sm font-black uppercase tracking-wider">ROI por mercado</p><p className="mt-1 text-[10px] text-zinc-600">Performance histórica observada, sem extrapolação garantida</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead><tr className="border-b border-line text-[9px] uppercase text-zinc-600"><th className="px-5 py-3">Mercado</th><th>ROI</th><th>Yield</th><th>Win Rate</th><th>Lucro</th><th>Drawdown</th><th>Entradas</th></tr></thead><tbody>{report.markets.map((item) => <tr key={item.period} className="border-b border-line/60"><td className="px-5 py-4 font-black">{item.period}</td><td className={item.roi >= 0 ? "text-neon" : "text-red-400"}>{item.roi.toFixed(2)}%</td><td>{item.yield.toFixed(2)}%</td><td>{item.winRate.toFixed(1)}%</td><td>{item.profit.toFixed(2)}u</td><td>{item.drawdown.toFixed(2)}u</td><td>{item.entries}</td></tr>)}</tbody></table></div></section>
    <section className="card mt-6 p-5"><div className="flex items-center gap-3"><BrainCircuit className="text-gold"/><div><p className="label">Evolução do modelo</p><h2 className="font-black">Performance mensal</h2></div></div><div className="mt-5 grid gap-3 md:grid-cols-3">{report.evolution.length ? report.evolution.map((item) => <div key={item.month} className="rounded-xl border border-line p-4 text-xs"><b>{item.month}</b><p className="mt-3 text-zinc-500">ROI <span className="float-right text-white">{item.roi.toFixed(2)}%</span></p><p className="mt-2 text-zinc-500">Win Rate <span className="float-right text-white">{item.winRate.toFixed(1)}%</span></p><p className="mt-2 text-zinc-500">Entradas <span className="float-right text-white">{item.entries}</span></p></div>) : <p className="text-xs text-zinc-600">A evolução aparecerá após as primeiras liquidações alimentarem o dataset.</p>}</div></section>
    <div className="mt-6 rounded-xl border border-line bg-white/[.02] p-4 text-[11px] leading-relaxed text-zinc-500">Relatório estatístico e probabilístico. Desempenho passado não garante resultados futuros, lucro ou green. Aposte com responsabilidade.</div>
  </>;
}
