import { Activity, ArrowDownRight, ArrowUpRight, Download, FlaskConical, Percent, ShieldAlert, TrendingDown, TrendingUp } from "lucide-react";
import { PageTitle } from "@/components/ui";
import { historicalBacktestData } from "@/data/backtestData";
import { buildBacktestReport } from "@/lib/backtestEngine";
import { RoiHeatmap } from "@/components/RoiHeatmap";
import { WeightCalibration } from "@/components/WeightCalibration";

const report = buildBacktestReport(historicalBacktestData);

export default function GreenLabPage() {
  const metrics = [
    { label: "ROI", value: `${report.metrics.roi >= 0 ? "+" : ""}${report.metrics.roi.toFixed(2)}%`, detail: "sobre banca inicial de 100u", icon: TrendingUp, tone: report.metrics.roi >= 0 ? "text-neon" : "text-red-400" },
    { label: "Yield", value: `${report.metrics.yield >= 0 ? "+" : ""}${report.metrics.yield.toFixed(2)}%`, detail: "lucro por unidade apostada", icon: Percent, tone: report.metrics.yield >= 0 ? "text-neon" : "text-red-400" },
    { label: "Win Rate", value: `${report.metrics.winRate.toFixed(2)}%`, detail: `${report.metrics.greens} greens em ${report.metrics.entries}`, icon: Activity, tone: "text-gold" },
    { label: "Lucro acumulado", value: `${report.metrics.accumulatedProfit >= 0 ? "+" : ""}${report.metrics.accumulatedProfit.toFixed(2)}u`, detail: "stake fixa de 1 unidade", icon: ArrowUpRight, tone: report.metrics.accumulatedProfit >= 0 ? "text-neon" : "text-red-400" },
    { label: "Drawdown máximo", value: `${report.metrics.maxDrawdown.toFixed(2)}u`, detail: "maior queda entre picos", icon: TrendingDown, tone: "text-red-400" },
  ];
  return <><PageTitle eyebrow="Laboratório quantitativo" title="Green Lab" description="Backtest reproduzível para medir se score e valor esperado mantêm desempenho após a liquidação." action={<a href="/api/green-lab/report" className="flex items-center gap-2 rounded-xl bg-neon px-5 py-3.5 text-[10px] font-black uppercase tracking-wider text-black"><Download size={15}/> Gerar PDF executivo</a>}/>
    <div className="mb-5 flex gap-3 rounded-xl border border-amber-400/20 bg-amber-400/[.05] p-4 text-[11px] leading-relaxed text-amber-200"><ShieldAlert size={17} className="shrink-0"/><span>Backtest demonstrativo com 96 registros sintéticos e determinísticos. Ele valida o pipeline matemático, mas não substitui dados históricos licenciados.</span></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(({label,value,detail,icon:Icon,tone}) => <div key={label} className="card p-5"><div className="flex justify-between"><p className="label">{label}</p><Icon size={16} className={tone}/></div><strong className={`mt-4 block text-3xl ${tone}`}>{value}</strong><p className="mt-1 text-[10px] text-zinc-600">{detail}</p></div>)}</div>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-line p-5"><p className="text-sm font-black uppercase tracking-wider">Filtro de qualidade</p><p className="mt-1 text-[10px] text-zinc-600">Comparação de score mínimo x EV mínimo</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b border-line text-[9px] uppercase text-zinc-600"><th className="px-5 py-3">Score</th><th>EV mínimo</th><th>Entradas</th><th>Win Rate</th><th>Yield</th><th>Lucro</th><th>Drawdown</th></tr></thead><tbody>{report.qualityMatrix.map((row) => <tr key={`${row.score}-${row.ev}`} className="border-b border-line/60"><td className="px-5 py-3 font-black">{row.score}+</td><td className="text-gold">{(row.ev*100).toFixed(0)}%+</td><td>{row.entries}</td><td>{row.winRate.toFixed(1)}%</td><td className={row.yield >= 0 ? "font-black text-neon" : "font-black text-red-400"}>{row.yield >= 0 ? "+" : ""}{row.yield.toFixed(1)}%</td><td>{row.accumulatedProfit.toFixed(2)}u</td><td>{row.maxDrawdown.toFixed(2)}u</td></tr>)}</tbody></table></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><RoiHeatmap data={report.heatmap}/><WeightCalibration/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="card overflow-hidden"><div className="border-b border-line p-5"><p className="text-sm font-black uppercase tracking-wider">Ranking de mercados</p><p className="mt-1 text-[10px] text-zinc-600">Ordenado por yield e taxa de acerto</p></div><div className="divide-y divide-line/60">{report.marketRankings.map((market,index) => <div key={market.market} className="grid grid-cols-[32px_1fr_auto_auto] items-center gap-3 p-4 text-xs"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/5 text-[10px] font-black text-zinc-500">{index+1}</span><div><strong>{market.market}</strong><span className="mt-1 block text-[9px] text-zinc-600">{market.entries} entradas</span></div><div className="text-right"><p className="label">Yield</p><strong className={market.yield >= 0 ? "text-neon" : "text-red-400"}>{market.yield.toFixed(1)}%</strong></div><div className="text-right"><p className="label">Acerto</p><strong>{market.winRate.toFixed(1)}%</strong></div></div>)}</div></section><section className="space-y-6"><div className="card p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-neon/10 text-neon"><ArrowUpRight/></div><div><p className="label">Mais lucrativo</p><h3 className="mt-1 text-lg font-black">{report.bestMarket?.market}</h3></div></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-line pt-4 text-center"><div><p className="label">Yield</p><strong className="text-neon">{report.bestMarket?.yield.toFixed(1)}%</strong></div><div><p className="label">Win Rate</p><strong>{report.bestMarket?.winRate.toFixed(1)}%</strong></div><div><p className="label">Lucro</p><strong>{report.bestMarket?.accumulatedProfit.toFixed(2)}u</strong></div></div></div><div className="card p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-red-500/10 text-red-400"><ArrowDownRight/></div><div><p className="label">Menos lucrativo</p><h3 className="mt-1 text-lg font-black">{report.worstMarket?.market}</h3></div></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-line pt-4 text-center"><div><p className="label">Yield</p><strong className="text-red-400">{report.worstMarket?.yield.toFixed(1)}%</strong></div><div><p className="label">Win Rate</p><strong>{report.worstMarket?.winRate.toFixed(1)}%</strong></div><div><p className="label">Lucro</p><strong>{report.worstMarket?.accumulatedProfit.toFixed(2)}u</strong></div></div></div><div className="card flex items-center gap-4 p-5"><FlaskConical className="text-gold"/><p className="text-[10px] leading-relaxed text-zinc-500">Os filtros com poucas entradas devem ser interpretados com cautela. Amostras pequenas podem produzir ROI extremo sem estabilidade estatística.</p></div></section></div>
  </>;
}
